version: '3'
services:
  discovery:
    image: consul:1.7
    ports:
      - 8500:8500

  scb-consul-remote-service:
    image: sovcombank-spring/scb-consul-remote-service
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery
    depends_on:
      - discovery

  scb-consul-local-service:
    image: sovcombank-spring/scb-consul-local-service
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery
    depends_on:
      - discovery
      - postgres

  scb-consul-gateway:
    image: sovcombank-spring/scb-consul-gateway
    ports:
      - 8080:8080
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery
    depends_on:
      - discovery

  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_DB=ib
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./create-schema-init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - 5432:5432
