spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    consul:
      discovery:
        register: false
      host: 172.16.9.93
      port: 8500
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8080

